name: Production deployment

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ecr.wmdbox.cloud
  IMAGE_NAME_WEB: tainabichler-web
  CAPHOVER_URL: captain.app.wmdbox.cloud

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login into ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Web to ${{ env.REGISTRY }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}:latest

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i -g caprover
      - run: caprover deploy -h ${{ env.CAPHOVER_URL }} -p ${{ secrets.CAPROVER_TOKEN }} -a tainabichler-com-br --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB2 }}:latest
      - run: sleep 30